postgres:
  image: postgres:12
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: passwd
    POSTGRES_DB: fintech
#    PGDATA: /data/postgres
  volumes:
    - ./migration/20220114153446_create_author.up.sql:/docker-entrypoint-initdb.d/init.sql
#    - ./postgres:/data/postgres
  ports:
    - "5442:5432"

# поднять контейнер docker-compose up -d (запустился и светрнулся)
# остановить конейнер docker-compose stop
# остановить конейнер и удалить образ  docker-compose down